### ISSUE TITLE
Fresh Meat Stack buff causes NRE

### ISSUE THREAD

**Issue by MissPotato** [CSOLYOO/RoR1ItemRework#1]
First off, I would like to apologize for using your RoR1ItemRework github to report an issue for a different mod. However, I could not find any other way to contact you. When attempting to fight the final boss, Mithrix, the game fails to spawn him in and spams consoles with errors. From what I can gather from the log the boss is checking items and when it comes across this item it is unable to handle the "OnCharacterDeath" call for the prep stage of "killAllMonsters".

The first error, and probably the important one is here: https://pastebin.com/enMCTc08 

The whole log is posted here however I had to trim the file because it was too large for pastebin: https://pastebin.com/qbyNeyKZ

**Comment by CSOLYOO** [comment]
I try to reappear your description, but failed. I upload a new version and seems to be work properly when face mithrix. You can try my new version.

**Comment by MissPotato** [comment]
This seems to have fixed it! I was able to fight Mithrix with no NRE!
